- examples/vue-example-app/src/components/utils/getData.js
Replace data url from http://stat.data.abs.gov.au to our proxy server.
Fixed below issue when load data from none https url.
```Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.```
Manual check.
> fix: replace example data url to https

- package.json
- src/test/__snapshots__/storyshots.test.js.snap
- yarn.lock
Fixed incorrect yarn lock file which contains several Ripple versions.
We should only have one Ripple version required.
no
> fix: multiple ripple versions

- packages/AddressSearch/index.vue
- packages/AddressSearch/utils/getAddresses.js
- packages/AddressSearchMap/AddressSearchMap.stories.mdx
- packages/AddressSearchMap/AddressSearchMap.vue
- packages/AddressSearchMap/LICENSE
- packages/AddressSearchMap/README.md
- packages/AddressSearchMap/index.js
- packages/AddressSearchMap/package.json
- packages/AddressSearchMap/utils/getAreas.js
- packages/AreaSearch/index.js
- packages/AutoComplete/index.vue
- packages/map-core/MapVectorLayer.vue
- packages/map-core/index.js
- packages/map-core/lib/ol.js
- src/test/__snapshots__/storyshots.test.js.snap
This PR adds a map based address search component.
Storyshot tests have been updated, but unit tests have not yet been implemented.
> feat: address search map component

- examples/vue-example-app/public/index.html
- examples/vue-example-app/src/App.vue
- examples/vue-example-app/src/components/MapLayout.vue
- packages/AddressSearch/AddressSearch.stories.mdx
- packages/AddressSearch/index.vue
- packages/AddressSearch/utils/getAddresses.js
- packages/AddressSearchMap/AddressSearchMap.vue
- packages/AutoComplete/SearchResults.vue
- packages/map-core/index.vue
> feat: tidy up of address search; set focus on map after a search

- packages/AddressSearchMap/AddressSearchMap.vue
Disable flex on IE11 for search box
It cause unexpected style issue on IE11
> fix: IE11 overflow issue

- packages/AddressSearchMap/AddressSearchMap.vue
> fix: resolve issue with layer fill colour in IE

- CONTRIBUTING.md
- packages/Examples/AreaWithData.vue
- packages/Examples/IncomeData.vue
* style: tidy up layout of examples 1 and 3 for small screens
* docs: add 'lerna run build' step in release workflow
> style: fix layout of examples for small mobile view (myvic-109) (#91)

- packages/AddressSearchMap/AddressSearchMap.vue
- packages/AutoComplete/index.vue
- src/test/__snapshots__/storyshots.test.js.snap
Swapped the mapbox basemap in the AddressSearchMap component with Vicmap WMS. Did not use the TILED option because there is an issue with the vicmap basemap requests after zooming in to an address (the issue seems to be caused by the bounding box values).
Added zIndex values for all layers in the component to force correct drawing order.
Fixed a CSS bug with the autocomplete container.
Tested in storybook
> feat: swap address search mapbox basemap with vicmap

- examples/vue-example-app/package.json
- examples/vue-example-app/yarn.lock
> fix: update address-search-map package in vue-example-app

- packages/AddressSearch/AddressSearch.stories.mdx
- packages/AddressSearch/index.vue
- packages/AddressSearch/utils/getAddresses.js
- packages/AddressSearchMap/AddressSearchMap.stories.mdx
- packages/AddressSearchMap/AddressSearchMap.vue
Added support for Vicmap Address API geocoder to the AddressSearch component, and configured the AddressSearchMap component to be able to use the new API.
This change should address availability issues in the current DELWP geocoder
> Added Vicmap Address API geocoder to AddressSearch

- proxy/app.js
- proxy/test/integration/address.spec.js
Added address suggestion API to proxy server.
The API gateway has some issue which client side request won't work in IE.
> chore: added proxy for address api

- proxy/app.js
This is a hotfix with same change in https://github.com/dpc-sdp/myvic-components/pull/107
> chore: add address proxy to production

- packages/AddressSearch/AddressSearch.stories.mdx
- packages/AddressSearch/index.vue
- packages/AddressSearch/utils/getAddresses.js
- packages/AddressSearchMap/AddressSearchMap.stories.mdx
- packages/AddressSearchMap/AddressSearchMap.vue
Changed address search endpoint to proxy server
> fix: changed address search endpoint to proxy

- packages/AddressSearch/AddressSearch.stories.mdx
- packages/AddressSearch/index.vue
- packages/AddressSearch/utils/getAddresses.js
- packages/AddressSearchMap/AddressSearchMap.stories.mdx
- packages/AddressSearchMap/AddressSearchMap.vue
- revert #109 
- Replace api.vic.gov.au to CDN api.sdp.vic.gov.au 
For bypass api.vic.gov.au IE11 support issue
> chore: use cdn for api.vic.gov.au

- packages/AddressSearchMap/AddressSearchMap.stories.mdx
- packages/AddressSearchMap/AddressSearchMap.vue
- src/test/__snapshots__/storyshots.test.js.snap
Added an option to choose which basemap to use in the AddressSearchMap component (Vicmap or Mapbox). When using the Mapbox basemap the watermark and attributions for Mapbox should also appear.
Storyshot tests updated
> feat: Add option to choose Vicmap or Mapbox basemap on AddressSearchMap

- examples/vue-example-app/src/components/MapLayout.vue
- packages/AutoComplete/index.vue
> fix: change onchange to 1s

- packages/AddressSearchMap/AddressSearchMap.vue
Update 25k map label as required
> chore: update 25k map label

- packages/map-core/Map.stories.mdx
- packages/map-core/MapIndicator.vue
- packages/map-core/MapVectorTileLayer.stories.mdx
- packages/map-core/package.json
- src/test/__snapshots__/storyshots.test.js.snap
- yarn.lock
> feat: add support for html content in map popups

- packages/map-core/MapVectorLayer.vue
> fix: expose zoom duration as property on vector layer

- examples/vue-example-app/src/components/MapLayout.vue
> chore: disable map boundary

- packages/AutoComplete/__tests__/AutoComplete.test.js
- packages/ToggleList/ToggleItem.vue
- packages/map-core/MapVectorLayer.stories.mdx
- packages/map-core/MapVectorLayer.vue
- packages/map-core/lib/ol.js
- packages/map-core/styles/styles.js
- src/test/__snapshots__/storyshots.test.js.snap
- Add more props to the MapVectorLayer component to enable clustering of point features and add default clustering configuration and styles
- adjust styling of ToggleList items to handle long text gracefully
- add fallback for null colours in map component (this might occur when the sass import fails)
- fix test for Autocomplete component (not sure how this issue was introduced)
this change supports the creation of the Kinder training map in vic.gov.au by enabling clustering in MapVectorLayer
updated storybook with a new story showcasing the clustering functionality
> feat: vector layer clustering

- packages/data-driven-component/module.js
Added module config to transpile Map dependencies for IE11
> fix: added module config to transpile Map dependencies for IE11

- packages/data-driven-component/DataDriven.vue
- packages/data-driven-component/README.md
MYVIC-114
Merge patch in vic-gov-au for kinder map back to here.
https://github.com/dpc-sdp/vic-gov-au/blob/develop/patches/%40dpc-sdp%2Bmyvic-data-driven-component%2B1.8.1.patch
Tested in kinder map already.
> [MYVIC-114] Datadriven IE support configuration

- .circleci/config.yml
- package.json
- packages/AddressSearch/__tests__/AddressSearch.test.js
- packages/AreaSearch/__tests__/AreaSearch.test.js
- packages/AutoComplete/__tests__/AutoComplete.test.js
- packages/AutoComplete/__tests__/SearchResults.test.js
- packages/BarChart/__tests__/BarChart.test.js
- packages/DataBlock/__tests__/DataBlock.test.js
- packages/DataBlock/__tests__/DataItem.test.js
- packages/Examples/__tests__/AreaWithData.test.js
- packages/Examples/__tests__/AreaWithMap.test.js
- packages/Examples/__tests__/IncomeData.test.js
- packages/LineChart/__tests__/LineChart.test.js
- packages/PieChart/__tests__/PieChart.test.js
- packages/ToggleList/__tests__/ToggleList.test.js
- packages/TreeMap/__tests__/TreeMap.test.js
- packages/global/components/__tests__/ChartDescription.test.js
- packages/global/components/__tests__/ChartWrapper.test.js
- packages/global/components/__tests__/Error.test.js
- packages/map-core/__tests__/Map.test.js
- src/test/__snapshots__/storyshots.test.js.snap
- yarn.lock
> fix: fix broken tests

- packages/ToggleList/ToggleItem.vue
- packages/ToggleList/ToggleList.stories.mdx
- packages/ToggleList/ToggleList.vue
- src/test/__snapshots__/storyshots.test.js.snap
Add the option to pass in custom colors to the toggle list items. This enables us to use more colors than what ripple allows.
Needed for the VSBA project where each toggle list item must correspond to a specific marker colour in the map
The default story has been updated to show a custom colour in one of the toggle list items
> feat: custom toggle list colors

- packages/AddressSearchMap/AddressSearchMap.vue
https://digital-engagement.atlassian.net/browse/SDPA-5291
I want to test http://example.pr-161.myvic-components.sdp2.sdp.vic.gov.au/
on IE browser and I am not not able to click the Microsoft Edge link
I suspect that .myvic-address-search-map__address-search-container needs to be adjusted in order to not cover IE alert.
Hiding the search is good enough to resolve this because the map is hidden anyway in IE11
- [ X] Bug fix (non-breaking change which fixes an issue)
> [SDPA-5291] hiding the search when browser is IE

- packages/AreaSearch/AreaSearch.stories.mdx
- packages/AreaSearch/index.vue
- packages/AreaSearch/storiesConstants.js
- packages/AreaSearch/utils/getAreas.js
- src/test/__snapshots__/storyshots.test.js.snap
You can know optionally disable the region and LGA results from the AreaSearch
Needed for VSBA
new storybook story
> feat: added noLgaOrRegion option to AreaSearch

- examples/vue-example-app/src/components/MapLayout.vue
Removes metro boundary from the radius map.
> Remove metro boundary

- examples/vue-example-app/src/components/ExampleSite.vue
- examples/vue-example-app/src/router/index.js
- packages/Examples/AreaWithData.vue
- packages/Examples/AreaWithMap.vue
- packages/Examples/IncomeData.vue
- src/test/__snapshots__/storyshots.test.js.snap
resolves MYVIC-116
updates the long description URLs. This was needed because the example page has been moved to the /demo route
> fix: update long description URLs

- packages/AddressSearchMap/AddressSearchMap.vue
- packages/AutoComplete/index.vue
- packages/global/mapIcons/iconLibrary.js
- packages/map-core/Map.stories.mdx
- packages/map-core/MapIndicator.vue
- packages/map-core/index.vue
- packages/map-core/lib/ol.js
- packages/map-core/styles/styles.js
- add Geolocation control to map and new prop to activate it
- fix bugs with positioning of map controls
- add geolocation point style and adjust other styles
- add animation to map zoom
- change sorting of autocomplete
needed for coronavirus map
new map story on Geolocation
> feat: coronavirus additional features

- packages/data-driven-component/DataDriven.vue
- packages/map-core/Map.stories.mdx
- packages/map-core/index.vue
- adds new prop `popupFeature` to map with two-way binding
- adjusts map center on "popups floating left" example
- changes style of data driven component heading
- adjusts styles of map controls
> feat: coronavirus more enhancements and fixes

- examples/vue-example-app/src/components/MapLayout.vue
> [SDPSUP-3333] Readd metro boundary

- packages/map-core/index.vue
> [SDPA-5555] Adds label for geolocation button

- Dockerfile.example
JIRA: https://digital-vic.atlassian.net/browse/SDPAP-6719
- Just bumping the node version in Dockerfile.example to a version that supports the node-sass version being used, also brings it inline with Dockerfile.storybook
- The develop deploys aren't currently working due the incompatability of `node` and  `node-sass` versions
> [SDPAP-6719] bump example node version

- packages/map-core/MapVectorLayer.vue
Ticket: https://digital-vic.atlassian.net/browse/SDPAP-7089
Maps markers we're disappearing when zooming in and out of the budget site, this is due to the animating of clusters which has been causing issues in general and is already disabled on small screens because of said issues.
This PR just removes animated clusters from all screen sizes which fixes the disappearing markers issue.
- See https://digital-vic.atlassian.net/browse/SDPAP-7089 
- This has been tested on the following budget branch https://app.pr-175.budget-vic-gov-au.sdp4.sdp.vic.gov.au/ 
- And can also be testing in storybook https://storybook.pr-209.myvic-components.sdp4.sdp.vic.gov.au/?path=/story/maps-vector-layer--alternative-cluster-style-and-behaviour
> [SDPAP-7089] remove animation from clusters

- package.json
- Remove bump version from package.json
> fix: remove bump version

- packages/AddressSearch/utils/getAddresses.js
Jira: https://digital-vic.atlassian.net/browse/SDPAP-7792
Update address search URL
> [SDPAP-7792] update address search URL
